### ISSUE TITLE
Testcase 1: Check if input file exists 

### ISSUE THREAD

**Issue by Gadjeid** [Gadjeid/BBC-News-Article-Scrapper#1]
Test case for checking file input provided by user. This file should be present in Data/unprocessed.

**Comment by amorrisCS** [comment]
In module_1/file_open.py lines 9-18, 

Try catch block implemented to ensure a file by the user entered name exists. 
If filename exists, the file is read.
If filename does not exist, the message "File {filename} not found" is displayed to the user.
