### ISSUE TITLE
Testcase 3: Check if links are valid

### ISSUE THREAD

**Issue by Gadjeid** [Gadjeid/BBC-News-Article-Scrapper#3]
Test case for checking if links read in from the user inputted .txt file are valid. Should return status code 200.

**Comment by amorrisCS** [comment]
In module_2/link_proccess.py on lines 22-83,

Implemented if-else to see if links are valid.
If valid, article is processed.
If invalid, the link is skipped, a message saying "Failed to retrieve the page. Status Code:  {response.status_code}", and iteration continues.

**Comment by amorrisCS** [comment]
In module_2/link_proccess.py on lines 22-83,

Implemented if-else to see if links are valid.
If valid, article is processed.
If invalid, the link is skipped, a message saying "Failed to retrieve the page. Status Code:  {response.status_code}", and iteration continues.
