### ISSUE TITLE
Testcase 5: Check if output file is output to output folder

### ISSUE THREAD

**Issue by amorrisCS** [Gadjeid/BBC-News-Article-Scrapper#5]
Test case for ensuring that the output file containing article scraps exists within the desired folder.

**Comment by Gadjeid** [comment]
In module_2/link_process.py on lines 83-85,

Implemented if-else to check if output file is correctly output to output folder.
If output file is found in output folder, print "article {index+1} scrapped, output in {output_folder}".
If output file is not found in output folder, print "Failed to save article scrap for article {index+1}".
