### ISSUE TITLE
Testcase 6: Check if output folder for summaries exists

### ISSUE THREAD

**Issue by Gadjeid** [Gadjeid/BBC-News-Article-Scrapper#6]
Test case for checking if output folder for ai summaries exists within the file structure.

**Comment by amorrisCS** [comment]
In module_3/ai_summary.py on lines 22-24,

Implemented if statement to check if the desired folder exists within the file structure.
If the file exists already, then continue "summarize_articles" function.
If the file does not already exist, then it is created.
