### ISSUE TITLE
Testcase 7: Check if headline is in output file

### ISSUE THREAD

**Issue by Gadjeid** [Gadjeid/BBC-News-Article-Scrapper#7]
Test case for checking if the output file from article scrap contains the headline. Should return "Headline: {content}".

**Comment by amorrisCS** [comment]
In module_3/ai_summary.py on lines 34-35,

Implemented if-else statements for ensuring that the line begins with "Headline: ".
If it does, save it as "title" variable and continue.
If it does not, add line to content variable and continue.
