### ISSUE TITLE
Testcase 8: Check if output file is output to output folder

### ISSUE THREAD

**Issue by amorrisCS** [Gadjeid/BBC-News-Article-Scrapper#8]
Test case for ensuring that the output file containing AI summary exists within the desired folder.

**Comment by Gadjeid** [comment]
In module_3/ai_summary.py on lines 50-53,

Implemented if-else to check if output file (summary) is correctly output to output folder.
If output file is found in output folder, print "article {index} scrapped, output in {output_folder}".
If output file is not found in output folder, print "Failed to save article scrap for article {index}".
